# vim ft=yaml
# travis-ci.org definition for Fail2Ban build
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_install:
  - sudo apt-get update -qq
install:
  - pip install pyinotify
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then sudo apt-get install -qq python-gamin; fi
  - pip install -q coveralls
script:
  - export PYTHONPATH="$PYTHONPATH:/usr/share/pyshared:/usr/lib/pyshared/python$TRAVIS_PYTHON_VERSION"
  - coverage run --rcfile=.travis_coveragerc setup.py test
after_success:
# Coverage config file must be .coveragerc for coveralls
  - cp -v .travis_coveragerc .coveragerc
  - coveralls
